# demo
GB_CONFIG_DEMO_LIBS 						= rt m dl pthread
GB_CONFIG_DEMO_CMD1 						=

# third party
GB_CONFIG_THIRD_HAVE_ZLIB 					= y
GB_CONFIG_THIRD_HAVE_OPENSSL 				= n
GB_CONFIG_THIRD_HAVE_POLARSSL 				= y
GB_CONFIG_THIRD_HAVE_MYSQL 					= n
GB_CONFIG_THIRD_HAVE_SQLITE3 				= y

