# demo
GB_CONFIG_DEMO_LIBS							= glut32 glu32 opengl32 polarssl sqlite3 z ws2_32
GB_CONFIG_DEMO_CMD1 						=

# third party
GB_CONFIG_THIRD_HAVE_GL 	 				= y
GB_CONFIG_THIRD_HAVE_GLUT 					= y
GB_CONFIG_THIRD_HAVE_SKIA 					= y
GB_CONFIG_THIRD_HAVE_X11 	 				= n
GB_CONFIG_THIRD_HAVE_SDL 					= n
GB_CONFIG_THIRD_HAVE_FRAMEBUFFER 			= n

# app window
GB_CONFIG_APP_WINDOW_NATIVE 				= y
GB_CONFIG_APP_WINDOW_SDL 					= n
GB_CONFIG_APP_WINDOW_FRAMEBUFFER 			= n

