# demo
GB_CONFIG_DEMO_LIBS							= m dl pthread
GB_CONFIG_DEMO_CMD1 						=

# device
GB_CONFIG_CORE_DEVICE_HAVE_GL 	 			= y		
GB_CONFIG_CORE_DEVICE_HAVE_BITMAP 			= y
GB_CONFIG_CORE_DEVICE_HAVE_SKIA 			= y

# third party
GB_CONFIG_THIRD_HAVE_ZLIB 					= y
GB_CONFIG_THIRD_HAVE_OPENSSL 				= n
GB_CONFIG_THIRD_HAVE_POLARSSL 				= y
GB_CONFIG_THIRD_HAVE_MYSQL 					= n
GB_CONFIG_THIRD_HAVE_SQLITE3 				= y

